from typing import Final

from pandas import DataFrame

OECD_INDUSTRY_CODE: Final[tuple[str, ...]] = (
    "D01T02",
    "D03",
    "D05T06",
    "D07T08",
    "D09",
    "D10T12",
    "D13T15",
    "D16",
    "D17T18",
    "D19",
    "D20",
    "D21",
    "D22",
    "D23",
    "D24",
    "D25",
    "D26",
    "D27",
    "D28",
    "D29",
    "D30",
    "D31T33",
    "D35",
    "D36T39",
    "D41T43",
    "D45T47",
    "D49",
    "D50",
    "D51",
    "D52",
    "D53",
    "D55T56",
    "D58T60",
    "D61",
    "D62T63",
    "D64T66",
    "D68",
    "D69T75",
    "D77T82",
    "D84",
    "D85",
    "D86T88",
    "D90T93",
    "D94T96",
    "D97T98",
)

OECD_ISIC_4_CORRESPONDING_DIVISION: Final[tuple[str, ...]] = (
    "01, 02",
    "3",
    "05, 06",
    "07, 08",
    "9",
    "10, 11, 12",
    "13, 14, 15",
    "16",
    "17, 18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31, 32, 33",
    "35",
    "36, 37, 38, 39",
    "41, 42, 43",
    "45, 46, 47",
    "49",
    "50",
    "51",
    "52",
    "53",
    "55, 56",
    "58, 59, 60",
    "61",
    "62, 63",
    "64, 65, 66",
    "68",
    "69 to 75",
    "77 to 82",
    "84",
    "85",
    "86, 87, 88",
    "90, 91, 92, 93",
    "94,95, 96",
    "97, 98",
)

OECD_CODE_DESCRIPTION: Final[tuple[str, ...]] = (
    "Agriculture, hunting, forestry",
    "Fishing and aquaculture",
    "Mining and quarrying, energy producing products",
    "Mining and quarrying, non-energy producing products",
    "Mining support service activities",
    "Food products, beverages and tobacco",
    "Textiles, textile products, leather and footwear",
    "Wood and products of wood and cork",
    "Paper products and printing",
    "Coke and refined petroleum products",
    "Chemical and chemical products",
    "Pharmaceuticals, medicinal chemical and botanical products",
    "Rubber and plastics products",
    "Other non-metallic mineral products",
    "Basic metals",
    "Fabricated metal products",
    "Computer, electronic and optical equipment",
    "Electrical equipment",
    "Machinery and equipment, nec",
    "Motor vehicles, trailers and semi-trailers",
    "Other transport equipment",
    "Manufacturing nec; repair and installation of machinery and equipment",
    "Electricity, gas, steam and air conditioning supply",
    "Water supply; sewerage, waste management and remediation activities",
    "Construction",
    "Wholesale and retail trade; repair of motor vehicles",
    "Land transport and transport via pipelines",
    "Water transport",
    "Air transport",
    "Warehousing and support activities for transportation",
    "Postal and courier activities",
    "Accommodation and food service activities",
    "Publishing, audiovisual and broadcasting activities",
    "Telecommunications",
    "IT and other information services",
    "Financial and insurance activities",
    "Real estate activities",
    "Professional, scientific and technical activities",
    "Administrative and support services",
    "Public administration and defence; compulsory social security",
    "Education",
    "Human health and social work activities",
    "Arts, entertainment and recreation",
    "Other service activities",
    "Activities of households as employers; undifferentiated goods- and services- producing activities of households for own use",
)


OECD_INPUT_OUTPUT_CODES = DataFrame(
    {
        "code": OECD_INDUSTRY_CODE,
        "isic_4_divisions": OECD_ISIC_4_CORRESPONDING_DIVISION,
        "description": OECD_CODE_DESCRIPTION,
    }
)


OECD_FINAL_DEMAND_COLUMN_NAMES: Final[tuple[str, ...]] = (
    "HFCE",
    "NPISH",
    "GGFC",
    "GFCF",
    "INVNT",
    "CONS_ABR",
    "CONS_NONRES",
    "EXPO",
    "IMPO",
    "TOTAL",
)

OECD_FINAL_DEMAND_DESCRIPTION: Final[tuple[str, ...]] = (
    "Final consumption expenditure of households",
    "Final consumption expenditure of non-profit institutions serving households",
    "Final consumption expenditure of general government",
    "Gross Fixed Capital Formation",
    "Changes in inventories",
    "Direct purchases abroad by residents (imports)",
    "Direct purchases by non-residents (exports)",
    "Exports (cross border)",
    "Imports (cross border)",
    "Total",
)

OECD_FINAL_DEMAND_CODES = DataFrame(
    {
        "code": OECD_FINAL_DEMAND_COLUMN_NAMES,
        "description": OECD_FINAL_DEMAND_DESCRIPTION,
    }
)

OECD_VALUE_ADDED_AND_OUTPUT_ROW_NAMES: Final[tuple[str, ...]] = (
    "TXS_IMP_FNL",
    "TXS_INT_FNL",
    "TTL_INT_FNL",
    "VALU",
    "OUTPUT",
    "TOTAL",
)

OECD_VALUE_ADDED_DESCRIPTION: Final[tuple[str, ...]] = (
    "Taxes less subsidies on intermediate and final products (paid in foreign countries)",
    "Taxes less subsidies on intermediate and final products (paid in domestic territory)",
    "Total intermediate consumption at purchasers’ prices",
    "Value added at basic prices: OUTPUT = TTL_INT_FNL + VALU",
    "Output at basic prices",
    "Total",
)

OECD_VALUE_ADDED_CODES = DataFrame(
    {
        "code": OECD_VALUE_ADDED_AND_OUTPUT_ROW_NAMES,
        "description": OECD_VALUE_ADDED_DESCRIPTION,
    }
)
