repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/hadialqattan/pycln
  rev: v1.1.0
  hooks:
    - id: pycln
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
    - id: mypy
