repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
      args: [--unsafe]
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/python-poetry/poetry
  rev: 1.7.0
  hooks:
    - id: poetry-check
    - id: poetry-lock

- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
    - id: pydocstyle
      entry: bash -c 'pydocstyle "$@" || true' --
      verbose: true
      additional_dependencies: ["pydocstyle[toml]"]
      args: [--config, ./pyproject.toml]

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
    - id: mypy
      verbose: true
      entry: bash -c 'mypy "$@" || true' --
