site_name: 'estios: Economic Spatial and Temporal Input-Output Systems'

nav:
- Home: index.md
- Installation: install.md
- 'Use':
    - 'Theory': theory.md
    - 'Data': data.md
    - 'Specification': spec.md
    - 'Scenarios': scenarios.md
    - 'License': license.md
- 'About': about.md
- '<tt>estios</tt>': estios/  # Must match GEN_DOC_PATH/ from docs/gen_ref_pages.py
- Issues: https://github.com/griff-rees/estios/issues

repo_url: https://github.com/griff-rees/estios/

watch:
- docs
- estios

theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
- search:
    min_search_length: 3
    lang: en
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: DOC_STRINGS.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          separate_signature: true
          show_signature_annotations: true
  # - bibtex:
  #     bib_file: !ENV ZOTERO_BIBTEX_URL
  #     csl_file: https://raw.githubusercontent.com/citation-style-language/styles/master/environment-and-planning.csl
    # cite_inline: true

markdown_extensions:
- admonition
- pymdownx.details
- mkdocs-typer
- abbr
- attr_list
- tables
- footnotes
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
      - name: math
        class: arithmatex
        format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format
          kwds:
            mode: generic
            tag: pre
# - pymdownx.snippets:
#     auto_append:
#       - docs/supplementary/glossary.md

extra_css:
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css

extra_javascript:
- javascripts/katex.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js
- javascripts/tablesort.js
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
