site_name: Regional Input-Output Economic Model
theme:
  name: material

nav:
    - Home: index.md
    - 'Information':
        - 'About': about.md
        - 'Data': data.md
        - 'Specification': spec.md
        - 'License': license.md
    - Installation: install.md
    - Issues: https://github.com/griff-rees/regional-input-output/issues

repo_url: https://github.com/griff-rees/regional-input-output/

plugins:
    - search:
        min_search_length: 3
        lang: en

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - admonition
    - pymdownx.details
    - pymdownx.superfences

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
