[tool.poetry]
name = "regional-input-output"
version = "0.1.0"
description = "RINO: Regional INput Output Economics"
authors = ["Dr Griffith Rees <grees@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
geopandas = "^0.10.2"

[tool.poetry.group]
[tool.poetry.group.visual.dependencies]
plotly = "^5.3.1"
jupyterlab = "^3.2.2"
jupyter-dash = "^0.4.0"

[tool.poetry.group.visual.dependencies.python-dotenv]
extras = ["cli"]
version = "^0.19.2"

[tool.poetry.group.server.dependencies]
fastapi = "^0.70.1"
uvicorn = "^0.16.0"
dash-auth = "^1.4.1"

[tool.poetry.group.server.dependencies.typer]
extras = ["all"]
version = "^0.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.1"
pre-commit = "^2.18.1"
pytest-cov = "^3.0.0"
openpyxl = "^3.0.9"
xlrd = "^2.0.1"
pytest-sugar = "^0.9.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov=regional_input_output
--cov-report=term:skip-covered
--pdbcls=IPython.terminal.debugger:TerminalPdb
"""

[tool.poetry.scripts]
region-io = "regional_input_output.cli:app"
