[tool.poetry]
name = "regional-input-output"
version = "0.1.0"
description = "rioecon: Regional Input Output ECONomics"
authors = ["Dr Griffith Rees <grees@turing.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
geopandas = "^0.10.2"
plotly = "^5.3.1"
jupyter-dash = "^0.4.0"
python-dotenv = {version = "^0.19.2", extras = ["cli"]}
fastapi = "^0.70.1"
uvicorn = "^0.16.0"
dash-auth = "^1.4.1"
typer = {version = "^0.4.0", extras = ["all"]}
openpyxl = "^3.0.9"
xlrd = "^2.0.1"
jupyterlab = "^3.2.2"
setuptools = "^62.6.0"
numpy = "^1.23.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1"
pre-commit = "^2.18.1"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"
mkdocs = "^1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov=regional_input_output
--cov-report=term:skip-covered
--pdbcls=IPython.terminal.debugger:TerminalPdb
"""

[tool.poetry.scripts]
region-io = "regional_input_output.cli:app"

# Pre-commit hooks related config.
[tool.pycln]
all = true
