[tool.poetry]
name = "regional-input-output"
version = "0.1.0"
description = "RINO: Regional INput Output Economics"
authors = ["Dr Griffith Rees <grees@turing.ac.uk>"]

[tool.poetry.dependencies]
python = "~3.9"
geopandas = "^0.10.2"
python-dotenv = {extras = ["cli"], version = "^0.19.2"}

[tool.poetry.dev-dependencies]
pytest = "^6.1"
jupyterlab = "^3.2.2"
plotly = "^5.3.1"
openpyxl = "^3.0.9"
xlrd = "^2.0.1"
pre-commit = "^2.15.0"
pytest-cov = "^3.0.0"
jupyter-dash = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=regional_input_output --cov-report=term:skip-covered"
