#!/usr/bin/env python
# -*- coding: utf-8 -*-

from datetime import datetime
from logging import getLogger
from typing import Final

from ..utils import MetaData

logger = getLogger(__name__)

REGIONS_ENGLAND: Final[tuple[str, ...]] = (
    "East Midlands",
    "East",
    "London",
    "North East",
    "North West",
    "South East",
    "South West",
    "West Midlands",
    "Yorkshire and The Humber",
)

METROPOLITAN_COUNTIES_ENGLAND: Final[tuple[str, ...]] = (
    "West Midlands",
    "West Yorkshire",
    "Merseyside",
    "Greater Manchester",
    "Tyne and Wear",
    "South Yorkshire",
)

SHIRE_COUNTIES_ENGLAND: Final[tuple[str, ...]] = (
    "Cambridgeshire",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Hampshire",
    "Hertfordshire",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Norfolk",
    "North Yorkshire",
    "Nottinghamshire",
    "Oxfordshire",
    "Somerset",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Warwickshire",
    "West Sussex",
    "Worcestershire",
)

UNITARY_AUTHORITIES_ENGLAND_OLD: Final[tuple[str, ...]] = (
    "Bournemouth",
    "Poole",
)

UNITARY_AUTHORITIES_ENGLAND: Final[tuple[str, ...]] = (
    # Missing:
    # Christchurch and Poole
    # Borough of Milton Keynes
    # North Northamptonshire
    # West Northamptonshire
    "Bath and North East Somerset",
    "Bedford",
    "Blackburn with Darwen",
    "Blackpool",
    "Bournemouth, Christchurch and Poole",  # 2019
    "Bracknell Forest",
    "Brighton and Hove",
    "Bristol",
    "Buckinghamshire",
    "Central Bedfordshire",
    "Cheshire East",
    "Cheshire West and Chester",
    "Cornwall",
    "County Durham",
    "Darlington",
    "Derby",
    "East Riding of Yorkshire",
    "Halton",
    "Hartlepool",
    "Herefordshire",
    "Isle of Wight",
    "Kingston upon Hull",
    "Leicester",
    "Luton",
    "Medway",
    "Middlesbrough",
    "Milton Keynes",
    "North East Lincolnshire",
    "North Lincolnshire",
    "North Northamptonshire",  # 2021
    "North Somerset",
    "Northumberland",
    "Nottingham",
    "Peterborough",
    "Plymouth",
    "Portsmouth",
    "Reading",
    "Redcar and Cleveland",
    "Rutland",
    "Shropshire",
    "Slough",
    "Southampton",
    "Southend-on-Sea",
    "South Gloucestershire",
    "Stockton-on-Tees",
    "Stoke-on-Trent",
    "Swindon",
    "Telford and Wrekin",
    "Thurrock",
    "Torbay",
    "Warrington",
    "West Berkshire",
    "West Northamptonshire",  # 2021
    "Wiltshire",
    "Windsor and Maidenhead",
    "Wokingham",
    "York",
)

NON_METROPOLITAN_COUNTIES_ENGLAND: Final[tuple[str, ...]] = (
    "Adur",
    "Allerdale",
    "Amber Valley",
    "Arun",
    "Ashfield",
    "Ashford",
    "Aylesbury Vale",
    "Babergh",
    "Barking and Dagenham",
    "Barnet",
    "Barnsley",
    "Barrow-in-Furness",
    "Basildon",
    "Basingstoke and Deane",
    "Bassetlaw",
    "Bexley",
    "Birmingham",
    "Blaby",
    "Bolsover",
    "Bolton",
    "Boston",
    "Bradford",
    "Braintree",
    "Breckland",
    "Brent",
    "Brentwood",
    "Broadland",
    "Bromley",
    "Bromsgrove",
    "Broxbourne",
    "Broxtowe",
    "Burnley",
    "Bury",
    "Calderdale",
    "Cambridge",
    "Camden",
    "Cannock Chase",
    "Canterbury",
    "Carlisle",
    "Castle Point",
    "Charnwood",
    "Chelmsford",
    "Cheltenham",
    "Cherwell",
    "Chesterfield",
    "Chichester",
    "Chiltern",
    "Chorley",
    "Christchurch",
    "City of London",
    "Colchester",
    "Copeland",
    "Corby",
    "Cotswold",
    "Coventry",
    "Craven",
    "Crawley",
    "Croydon",
    "Dacorum",
    "Dartford",
    "Daventry",
    "Derbyshire Dales",
    "Doncaster",
    "Dorset",
    "Dover",
    "Dudley",
    "Ealing",
    "East Cambridgeshire",
    "East Devon",
    "East Dorset",
    "East Hampshire",
    "East Hertfordshire",
    "East Lindsey",
    "East Northamptonshire",
    "East Staffordshire",
    "Eastbourne",
    "Eastleigh",
    "Eden",
    "Elmbridge",
    "Enfield",
    "Epping Forest",
    "Epsom and Ewell",
    "Erewash",
    "Exeter",
    "Fareham",
    "Fenland",
    "Folkestone and Hythe",
    "Forest Heath",
    "Forest of Dean",
    "Fylde",
    "Gateshead",
    "Gedling",
    "Gloucester",
    "Gosport",
    "Gravesham",
    "Great Yarmouth",
    "Greenwich",
    "Guildford",
    "Hackney",
    "Hambleton",
    "Hammersmith and Fulham",
    "Harborough",
    "Haringey",
    "Harlow",
    "Harrogate",
    "Harrow",
    "Hart",
    "Hastings",
    "Havant",
    "Havering",
    "Hertsmere",
    "High Peak",
    "Hillingdon",
    "Hinckley and Bosworth",
    "Horsham",
    "Hounslow",
    "Huntingdonshire",
    "Hyndburn",
    "Ipswich",
    "Isles of Scilly",
    "Islington",
    "Kensington and Chelsea",
    "Kettering",
    "King's Lynn and West Norfolk",
    "Kingston upon Thames",
    "Kirklees",
    "Knowsley",
    "Lambeth",
    "Lancaster",
    "Leeds",
    "Lewes",
    "Lewisham",
    "Lichfield",
    "Lincoln",
    "Liverpool",
    "Maidstone",
    "Maldon",
    "Malvern Hills",
    "Manchester",
    "Mansfield",
    "Melton",
    "Mendip",
    "Merton",
    "Mid Devon",
    "Mid Suffolk",
    "Mid Sussex",
    "Mole Valley",
    "New Forest",
    "Newark and Sherwood",
    "Newcastle upon Tyne",
    "Newcastle-under-Lyme",
    "Newham",
    "North Devon",
    "North Dorset",
    "North East Derbyshire",
    "North Hertfordshire",
    "North Kesteven",
    "North Norfolk",
    "North Tyneside",
    "North Warwickshire",
    "North West Leicestershire",
    "Northampton",
    "Northamptonshire",
    "Norwich",
    "Nuneaton and Bedworth",
    "Oadby and Wigston",
    "Oldham",
    "Oxford",
    "Pendle",
    "Preston",
    "Purbeck",
    "Redbridge",
    "Redditch",
    "Reigate and Banstead",
    "Ribble Valley",
    "Richmond upon Thames",
    "Richmondshire",
    "Rochdale",
    "Rochford",
    "Rossendale",
    "Rother",
    "Rotherham",
    "Rugby",
    "Runnymede",
    "Rushcliffe",
    "Rushmoor",
    "Ryedale",
    "Salford",
    "Sandwell",
    "Scarborough",
    "Sedgemoor",
    "Sefton",
    "Selby",
    "Sevenoaks",
    "Sheffield",
    "Solihull",
    "South Bucks",
    "South Cambridgeshire",
    "South Derbyshire",
    "South Hams",
    "South Holland",
    "South Kesteven",
    "South Lakeland",
    "South Norfolk",
    "South Northamptonshire",
    "South Oxfordshire",
    "South Ribble",
    "South Somerset",
    "South Staffordshire",
    "South Tyneside",
    "Southwark",
    "Spelthorne",
    "St Albans",
    "St Edmundsbury",
    "St. Helens",
    "Stafford",
    "Staffordshire Moorlands",
    "Stevenage",
    "Stockport",
    "Stratford-on-Avon",
    "Stroud",
    "Suffolk Coastal",
    "Sunderland",
    "Surrey Heath",
    "Sutton",
    "Swale",
    "Tameside",
    "Tamworth",
    "Tandridge",
    "Taunton Deane",
    "Teignbridge",
    "Tendring",
    "Test Valley",
    "Tewkesbury",
    "Thanet",
    "Three Rivers",
    "Tonbridge and Malling",
    "Torridge",
    "Tower Hamlets",
    "Trafford",
    "Tunbridge Wells",
    "Uttlesford",
    "Vale of White Horse",
    "Wakefield",
    "Walsall",
    "Waltham Forest",
    "Wandsworth",
    "Warwick",
    "Watford",
    "Waveney",
    "Waverley",
    "Wealden",
    "Wellingborough",
    "Welwyn Hatfield",
    "West Devon",
    "West Dorset",
    "West Lancashire",
    "West Lindsey",
    "West Oxfordshire",
    "West Somerset",
    "Westminster",
    "Weymouth and Portland",
    "Wigan",
    "Winchester",
    "Wirral",
    "Woking",
    "Wolverhampton",
    "Worcester",
    "Worthing",
    "Wychavon",
    "Wycombe",
    "Wyre Forest",
    "Wyre",
)


CENTRE_FOR_CITIES_2022_CITY_REGIONS: Final[dict[str, tuple[str, ...]]] = {
    "Aberdeen": ("Aberdeen",),
    "Aldershot": (
        "Rushmoor",
        "Surrey Heath",
    ),
    "Barnsley": ("Barnsley",),
    "Basildon": ("Basildon",),
    "Belfast": (
        "Belfast",
        "Lisburn and Castlereagh",
    ),
    "Birkenhead": ("Wirral",),
    "Birmingham": (
        "Birmingham",
        "Dudley",
        "Sandwell",
        "Solihull",
        "Walsall",
        "Wolverhampton",
    ),
    "Blackburn": ("Blackburn with Darwen",),
    "Blackpool": (
        "Blackpool",
        "Fylde",
    ),
    "Bournemouth": (
        "Dorset",
        "Bournemouth Christchurch and Poole",
    ),
    "Bradford": ("Bradford",),
    "Brighton": (
        "Adur",
        "Brighton and Hove",
    ),
    "Bristol": (
        "City of Bristol",
        "South Gloucestershire",
    ),
    "Burnley": (
        "Burnley",
        "Pendle",
    ),
    "Cambridge": ("Cambridge",),
    "Cardiff": ("Cardiff",),
    "Chatham": ("Medway",),
    "Coventry": ("Coventry",),
    "Crawley": ("Crawley",),
    "Derby": ("Derby",),
    "Doncaster": ("Doncaster",),
    "Dundee": ("Dundee",),
    "Edinburgh": ("Edinburgh",),
    "Exeter": ("Exeter",),
    "Glasgow": (
        "East Dunbartonshire",
        "East Renfrewshire",
        "Glasgow",
        "Renfrewshire",
    ),
    "Gloucester": ("Gloucester",),
    "Huddersfield": ("Kirklees",),
    "Hull": ("Kingston upon Hull",),
    "Ipswich": ("Ipswich",),
    "Leeds": ("Leeds",),
    "Leicester": (
        "Blaby",
        "Leicester",
        "Oadby and Wigston",
    ),
    "Liverpool": (
        "Knowsley",
        "Liverpool",
    ),
    "London": (
        "Barking and Dagenham",
        "Barnet",
        "Bexley",
        "Brent",
        "Bromley",
        "Broxbourne",
        "Camden",
        "City of London",
        "Croydon",
        "Dartford",
        "Ealing",
        "Elmbridge",
        "Enfield",
        "Epping Forest",
        "Epsom and Ewell",
        "Gravesham",
        "Greenwich",
        "Hackney",
        "Hammersmith and Fulham",
        "Haringey",
        "Harrow",
        "Havering",
        "Hertsmere",
        "Hillingdon",
        "Hounslow",
        "Islington",
        "Kensington and Chelsea",
        "Kingston upon Thames",
        "Lambeth",
        "Lewisham",
        "Merton",
        "Newham",
        "Redbridge",
        "Richmond upon Thames",
        "Runnymede",
        "Southwark",
        "Spelthorne",
        "Sutton",
        "Three Rivers",
        "Tower Hamlets",
        "Waltham Forest",
        "Wandsworth",
        "Watford",
        "Westminster",
        "Woking",
    ),
    "Luton": ("Luton",),
    "Manchester": (
        "Bolton",
        "Bury",
        "Manchester",
        "Oldham",
        "Rochdale",
        "Salford",
        "Stockport",
        "Tameside",
        "Trafford",
    ),
    "Mansfield": (
        "Ashfield",
        "Mansfield",
    ),
    "Middlesbrough": (
        "Middlesbrough",
        "Redcar and Cleveland",
        "Stockton-on-Tees",
    ),
    "Milton Keynes": ("Milton Keynes",),
    "Newcastle": (
        "Gateshead",
        "Newcastle upon Tyne",
        "North Tyneside",
        "South Tyneside",
    ),
    "Newport": (
        "Newport",
        "Torfaen",
    ),
    "Northampton": ("West Northamptonshire",),
    "Norwich": (
        "Broadland",
        "Norwich",
    ),
    "Nottingham": (
        "Broxtowe",
        "Erewash",
        "Gedling",
        "Nottingham",
    ),
    "Oxford": ("Oxford",),
    "Peterborough": ("Peterborough",),
    "Plymouth": ("Plymouth",),
    "Portsmouth": (
        "Portsmouth",
        "Fareham",
        "Gosport",
        "Havant",
    ),
    "Preston": (
        "Chorley",
        "Preston",
        "South Ribble",
    ),
    "Reading": (
        "Reading",
        "Wokingham",
    ),
    "Sheffield": (
        "Rotherham",
        "Sheffield",
    ),
    "Slough": ("Slough",),
    "Southampton": (
        "Eastleigh",
        "Southampton",
    ),
    "Southend": (
        "Castlepoint",
        "Southend-on-Sea",
        "Rochford",
    ),
    "Stoke": (
        "Newcastle-under-Lyme",
        "Stoke-on-Trent",
    ),
    "Sunderland": ("Sunderland",),
    "Swansea": (
        "Neath Port Talbot",
        "Swansea",
    ),
    "Swindon": ("Swindon",),
    "Telford": ("Telford and Wrekin",),
    "Wakefield": ("Wakefield",),
    "Warrington": ("Warrington",),
    "Wigan": ("Wigan",),
    "Worthing": ("Worthing",),
    "York": ("York",),
}


CENTRE_FOR_CITIES_2022_CITY_REGIONS_METADATA: Final[MetaData] = MetaData(
    name="Centre for Cities 2022 Primary Urban Areas (PUA)",
    year=2022,
    description=(
        "A hand transcription of a pdf listing all UK and "
        "Northern Ireland Primary Urban Areas (PUAs)"
    ),
    region="United Kingdom and Northern Ireland",
    authors={
        "Centre for Cities": "https://www.centreforcities.org/city-by-city/puas/",
        "Centre for Urban and Regional Development Studies (CURDS)": {
            "url": "https://www.ncl.ac.uk/curds/",
            "institution": "University of Newcastle",
        },
    },
    url="https://www.centreforcities.org/wp-content/uploads/2022/08/2022-PUA-Table.pdf",
    date_time_obtained=datetime(2022, 8, 3, 10, 27),
    # license=
)

logger.warning(f"License info for Centre for Cities data needed.")
